spring:
  application:
    name: jpa0820
  datasource:
    url: jdbc:h2:./db_dev;Mode=MySQL
    username: sa
    password:
    dirve-class-name: org.h2.Driver
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true # SQL 예쁘게 출력
        highlight_sql: true # SQL 색상 강조
        use_sql_comments: true # SQL에 주석 추가
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE